minimumReleaseAge: 10080 # 1 week

trustPolicy: no-downgrade
trustPolicyExclude:
  - "chokidar@4.0.3"
  - "semver@5.7.2 || 6.3.1"
  - "ts-api-utils@2.3.0"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
